VariantDir('build', '../src', duplicate=0)
env = Environment(CCFLAGS='-g')

# TODO, detect OS X and use clang++
env.Append( CXXFLAGS='-std=c++0x' )

# TODO, be able to load include paths from a config file
INCS = ['/home/dwkimm01/apps/include', '/usr/include/glib-2.0', '/usr/lib/i386-linux-gnu/glib-2.0/include', '/usr/include/libpurple']
# TODO, be able to load lib paths from a config file
LIBPATHS = ['/home/dwkimm01/apps/lib']
# TODO, depending on the system/lib versions we have to explicitly load diff libs
LIBS = ['boost_regex', 'boost_program_options', 'boost_signals', 'boost_system', 'ncurses', 'purple']
SRCS = Glob('build/*.cpp')

# Build executable
env.Program(SRCS, CPPPATH=INCS, LIBS=LIBS, LIBPATH=LIBPATHS)

